# Generated by Django 3.1.7 on 2021-03-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
