# Generated by Django 3.1.7 on 2021-03-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='collection_frequency',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='last_collection',
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='BinOperation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bin')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operation')),
            ],
        ),
    ]
